# Generated by Django 3.2 on 2021-07-10 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddElections',
            fields=[
                ('Election_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('Election_name', models.CharField(max_length=50)),
                ('Year', models.CharField(max_length=4)),
                ('Start_date', models.DateField()),
                ('End_date', models.DateField()),
                ('Start_time', models.TimeField()),
                ('End_time', models.TimeField()),
                ('State', models.CharField(max_length=30)),
                ('Seats', models.CharField(max_length=30)),
                ('Status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_img', models.ImageField(upload_to='pics/')),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('address', models.CharField(max_length=100)),
                ('phone_num', models.CharField(max_length=10)),
                ('Aadhar_card', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=40)),
                ('email', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('statecode', models.IntegerField()),
                ('seatcode', models.IntegerField()),
                ('partyname', models.CharField(max_length=20)),
                ('symbol', models.CharField(max_length=20)),
                ('vote_receive', models.IntegerField()),
                ('gender', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Voter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('middlename', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('voterid', models.CharField(max_length=20, unique=True)),
                ('passwd', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=30)),
                ('state', models.CharField(max_length=30)),
                ('statecode', models.IntegerField()),
                ('seatcode', models.IntegerField()),
                ('phone', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Election',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Candidate_Name', models.CharField(default='', max_length=30)),
                ('Election_Name', models.CharField(max_length=50)),
                ('Candidate_Username', models.CharField(max_length=20)),
                ('State', models.CharField(max_length=30)),
                ('Seat', models.CharField(max_length=30)),
                ('NoofVotes', models.PositiveBigIntegerField(default=0)),
                ('Candidate_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Voting.candidate')),
                ('Election_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Voting.addelections')),
            ],
        ),
    ]
