# Generated by Django 3.2 on 2021-07-10 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Voting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='election',
            name='Candidate_Id',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='election',
            name='Election_id',
            field=models.BigIntegerField(),
        ),
    ]
