# Generated by Django 3.2 on 2021-07-11 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Voting', '0002_auto_20210710_2338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voter',
            name='seatcode',
        ),
        migrations.AddField(
            model_name='voter',
            name='seatname',
            field=models.CharField(default='', max_length=30),
        ),
    ]
