# Generated by Django 3.2 on 2021-07-11 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Voting', '0003_auto_20210711_1055'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='seatname',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='seatcode',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='statecode',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='voter',
            name='statecode',
            field=models.IntegerField(default=0),
        ),
    ]
