# Generated by Django 3.2 on 2021-07-11 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Voting', '0004_auto_20210711_1232'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlreadyVoted',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Election_id', models.BigIntegerField()),
                ('Username', models.CharField(max_length=20)),
                ('Name', models.CharField(max_length=50)),
            ],
        ),
    ]
