# Generated by Django 3.2 on 2021-07-11 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Voting', '0005_alreadyvoted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alreadyvoted',
            name='Name',
        ),
    ]
