# Generated by Django 3.2 on 2021-07-14 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Voting', '0006_remove_alreadyvoted_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainElection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Election_Name', models.CharField(max_length=50)),
                ('State', models.CharField(max_length=30)),
                ('Status', models.IntegerField(default=0)),
                ('Year', models.CharField(max_length=10)),
                ('Start_date', models.DateField()),
                ('End_date', models.DateField()),
                ('Start_time', models.TimeField()),
                ('End_time', models.TimeField()),
            ],
        ),
        migrations.RemoveField(
            model_name='addelections',
            name='End_date',
        ),
        migrations.RemoveField(
            model_name='addelections',
            name='End_time',
        ),
        migrations.RemoveField(
            model_name='addelections',
            name='Start_date',
        ),
        migrations.RemoveField(
            model_name='addelections',
            name='Start_time',
        ),
        migrations.RemoveField(
            model_name='addelections',
            name='Status',
        ),
        migrations.AddField(
            model_name='addelections',
            name='MainElection_id',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='addelections',
            name='Year',
            field=models.CharField(max_length=10),
        ),
    ]
