# Generated by Django 3.2.8 on 2021-10-24 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Voting', '0008_election_mainelection_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeatDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SeatName', models.CharField(max_length=50)),
                ('State', models.CharField(max_length=50)),
                ('Current_MLA', models.CharField(max_length=50)),
                ('Current_MP', models.CharField(max_length=50)),
            ],
        ),
    ]
